name: ENV test
on:
  push:
    branches:
      - main
    paths:
      - 'scanner/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRETS_TEST: ${{ secrets.SECRETS_TEST}}
    steps:
    - name: ENV test
      run: |
        echo $SECRETS_TEST
