name: GitHub Actions Demo

on: workflow_dispatch
jobs:
 Actions-Hello-World:
   runs-on: self-hosted
   steps:
     - name: Curl URL
       run: |
         curl -H "accept\: application/json" \
         ${{secrets.SECRETS_TEST}}
