name: Vars
on: workflow_dispatch
jobs:
  print_env:
    runs-on: self-hosted
    name: Print env
    steps:
      - name: Curl URL
        run: |
          curl -H "accept\: application/json" \
          ${{secrets.SECRETS_TEST}}
